# Generated by Django 6.0.8 on 2026-08-23 19:44

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Payments are sequenced later (D1), but the price belongs to the book.')),
                ('is_published', models.BooleanField(default=False, help_text='Concierge onboarding works against a live database. Without this, a half-built book with three of eight chapters is immediately assignable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(help_text='1-based.')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to=core.models.chapter_upload_path)),
                ('text_content', models.TextField(blank=True, help_text="Extracted at upload. The companion's entire context (D13).", null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.book')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace', models.CharField(choices=[('slow', 'slow'), ('medium', 'medium'), ('fast', 'fast')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.models.generate_token, max_length=32, unique=True)),
                ('expires_at', models.DateTimeField(default=core.models.default_reset_expiry)),
                ('used_at', models.DateTimeField(blank=True, help_text='Set when the password actually changes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemporalGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.models.generate_token, max_length=32, unique=True)),
                ('expires_at', models.DateTimeField(default=core.models.default_grant_expiry)),
                ('unlock_at', models.DateTimeField(blank=True, help_text='The cadence seam. Always null until cadence lands (D1).', null=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='The FIRST open, not the last. An engagement signal, not analytics.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=64)),
                ('to_phone', models.CharField(help_text='A snapshot. A reader changes their number; logs record what happened.', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('failed', 'failed')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text="'sent' means the provider accepted it, NOT that it arrived.", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(blank=True, help_text='Null for account messages such as password reset — they have no chapter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.temporalgrant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_usage', to='core.temporalgrant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('book', 'order_index'), name='unique_chapter_index_per_book'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='one_order_per_user_per_book'),
        ),
        migrations.AddIndex(
            model_name='temporalgrant',
            index=models.Index(fields=['user', 'chapter'], name='core_tempor_user_id_2bd58b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['user', 'created_at'], name='core_messag_user_id_bd5097_idx'),
        ),
        migrations.AddIndex(
            model_name='chatusage',
            index=models.Index(fields=['date'], name='core_chatus_date_98c2d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatusage',
            constraint=models.UniqueConstraint(fields=('grant', 'date'), name='one_usage_row_per_grant_per_day'),
        ),
    ]
