# Generated by Django 6.0.8 on 2026-08-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_chapter_order_passwordresettoken_temporalgrant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalgrant',
            name='state',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('live', 'live'), ('opened', 'opened')], default='live', max_length=20),
        ),
    ]
