# Generated by Django 6.0.8 on 2026-09-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_temporalgrant_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Razorpay payment_link id. Empty for concierge-created orders.', max_length=100),
        ),
    ]
