# Generated by Django 6.0.8 on 2026-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_normalize_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='page_layout',
            field=models.JSONField(blank=True, help_text="Filled at upload by services/pages.py (D73): each page's size and rendered image, and the PDF's sections. Null until rendered; the reader cannot open a chapter without it.", null=True),
        ),
    ]
