# Generated by Django 6.0.8 on 2026-09-23 19:17

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reading_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, help_text='Proxied through the API, never linked directly (mandate 3).', upload_to=core.models.book_cover_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='sample_video',
            field=models.FileField(blank=True, help_text='Optional public sample, MP4 (D76). Anyone may watch it; no login.', upload_to=core.models.book_sample_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4']), core.models.validate_video_size]),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video',
            field=models.FileField(blank=True, help_text='Optional companion video, MP4 (D76). Gated with the chapter: it plays only for a live, owned grant.', upload_to=core.models.chapter_video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4']), core.models.validate_video_size]),
        ),
    ]
