# Generated by Django 6.0.8 on 2026-09-23 20:48

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_account_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.FileField(blank=True, help_text='Optional video for the whole book, MP4, for owners only (D83).', upload_to=core.models.book_video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4']), core.models.validate_video_size]),
        ),
    ]
