# Generated by Django 6.0.8 on 2026-09-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_book_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalgrant',
            name='unlock_at',
            field=models.DateTimeField(blank=True, help_text='When this chapter unlocks (D50). Null for chapter 1, which is delivered at purchase.', null=True),
        ),
        migrations.AddIndex(
            model_name='temporalgrant',
            index=models.Index(fields=['state', 'unlock_at'], name='core_tempor_state_c64272_idx'),
        ),
    ]
