# Generated by Django 6.0 on 2026-09-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_grant_cadence_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='E.164, e.g. +919876543210. Enables WhatsApp delivery and recovery.', max_length=20, null=True, unique=True),
        ),
    ]
