# Generated by Django 6.0 on 2026-09-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_phone_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_seed',
            field=models.CharField(blank=True, help_text='Overrides email as the identicon seed. NULL uses the email.', max_length=64, null=True),
        ),
    ]
